name: sencash
description: "Fintech wallet application for international money transfers"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^14.2.7
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
